name: SSH Server Connection

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ssh-connect:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Execute remote SSH commands using password
      uses: appleboy/ssh-action@v1
      with:
        host: gestionreg@gestionreg.com
        username: gestionreg
        password: D}HOHj^Q+YdX
        port: 22
        script: whoami
